/* src/features/Discovery/components/GravelPopup.tsx */
import Sparkline from "../../../components/RideGuide/widgets/Sparkline";

// 1. Define the interface with the names generated by utils.ts
export interface GravelPopupData {
  roadId: string;
  roadName: string;
  maintenanceLevel: string;
  miles: string;
  avgGrade: string;
  surfaceType: string;
  difficulty: string;
  vibe: string;
  elevationProfile: number[];
  status?: string;
}

interface GravelPopupProps {
  route: GravelPopupData | null;
  onClose: () => void;
}

export default function GravelPopup({ route, onClose }: GravelPopupProps) {
  if (!route) return null;

  return (
    <div className="gravel-popup-teaser shadow-2xl bg-slate-900 border border-slate-700 p-4 rounded-xl text-white">
      <button onClick={onClose} className="absolute top-2 right-2 text-slate-400 hover:text-white text-xl">×</button>
      
      <header className="mb-3">
        {/* Changed from .id to .roadId */}
        <span className="text-xs font-bold text-blue-400 tracking-widest uppercase">FS {route.roadId}</span>
        {/* Changed from .name to .roadName */}
        <h2 className="text-lg font-bold truncate">{route.roadName}</h2>
      </header>

      <div className="grid grid-cols-2 gap-4 mb-4">
        <div className="flex flex-col">
            <span className="text-[10px] text-slate-500 font-bold uppercase">Distance</span>
            {/* Changed from .distance to .miles */}
            <span className="text-sm font-mono">{route.miles} mi</span>
        </div>
        <div className="flex flex-col">
            <span className="text-[10px] text-slate-500 font-bold uppercase">Avg Grade</span>
            <span className="text-sm font-mono">{route.avgGrade}%</span>
        </div>
      </div>

      <div className="h-16 mb-4 bg-slate-800/50 rounded-lg p-1">
         {/* Changed from .id to .roadId */}
         <Sparkline routeID={route.roadId} />
      </div>

      <div className="border-t border-slate-700 pt-3">
        {/* Changed from .vibe to .vibe (Matches utils) */}
        <p className="text-[11px] text-slate-400 mb-2 italic">"{route.vibe}"</p>
        <button 
          className="w-full py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold uppercase tracking-tighter rounded transition-colors"
          onClick={() => window.location.href = `/report/${route.roadId}`}
        >
          Unlock Live Weather & Effort Guide
        </button>
      </div>
    </div>
  );
}