/* src/components/RideGuide/widgets/RouteConditions.tsx */
import { useWeatherData } from '../../../hooks/useWeatherData';

export default function RouteConditions({ routeID }: { routeID: string }) {
  const { data, loading } = useWeatherData(routeID);

  if (loading || !data?.ssdi) return <div className="rr-widget-conditions-root">...</div>;

  // 1. Pull the exact values processed by the weather_engine
  const { ssdi_score, condition, style_color} = data.ssdi;

  // 2. Use the style_color directly from the JSON for the Halo/Label
  const haloStyle = {
    color: style_color || '#333333', // Fallback to dark grey if missing
    textShadow: '0 0 4px white, 0 0 4px white, 0 0 4px white, 0 0 4px white',
    zIndex: 60,
    position: 'relative' as const
  };

  return (
    <div className="rr-widget-conditions-root">
      <div className="rr-cond-wheel-container">
        <div className="rr-cond-tire-bed" />
        
        {/* Using the SVG wheel generated by the engine */}
        <img 
          src={`/data/visualization/${routeID}_conditions_wheel.svg`} 
          className="rr-cond-wheel-svg"
          alt="Route Conditions"
        />

        <div className="rr-cond-hub-overlay">
          {/* Displaying the exact condition string from your QGIS logic */}
          <span className="rr-cond-hub-text " style={haloStyle}>
            {condition}
          </span>
        </div>
      </div>
    </div>
  );
}